package com.btrpa.radar;

import android.Manifest;import android.app.*;import android.bluetooth.*;import android.bluetooth.le.*;import android.content.*;import android.graphics.*;import android.location.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;import javax.crypto.*;import javax.crypto.spec.*;

public class MainActivity extends Activity{
  final Map<String,Device> devices=new HashMap<>(); LinearLayout list,setup; RadarView radar; TextView stats,warn; Button scanBtn; Scanner scanner; SettingsModel cfg=new SettingsModel(); Location bestLoc; Handler h=new Handler(); boolean scanning=false;
  public void onCreate(Bundle b){super.onCreate(b); scanner=new Scanner(); buildUi(); requestPerms();}
  void buildUi(){ScrollView root=new ScrollView(this); LinearLayout col=new LinearLayout(this); col.setOrientation(LinearLayout.VERTICAL); col.setPadding(24,24,24,24); col.setBackgroundColor(Color.rgb(5,7,13)); root.addView(col); TextView title=t("BTRPA RADAR",30,0xff00e5ff,true); col.addView(title); warn=t("IRK mode note: Android may mask real BLE random private addresses, so resolution depends on addresses exposed by this OS/device.",12,0xffffcc66,false); col.addView(warn); setup=new LinearLayout(this); setup.setOrientation(LinearLayout.VERTICAL); col.addView(setup); addControls(); radar=new RadarView(this); col.addView(radar,new LinearLayout.LayoutParams(-1,620)); stats=t("Idle",14,0xffa7f3ff,false); col.addView(stats); scanBtn=new Button(this); scanBtn.setText("START SCAN"); scanBtn.setOnClickListener(v->{if(scanning)stop();else start();}); col.addView(scanBtn); LinearLayout ex=new LinearLayout(this); ex.setGravity(Gravity.CENTER); for(String f:new String[]{"CSV","JSON","JSONL"}){Button b=new Button(this);b.setText("Share "+f);b.setOnClickListener(v->share(((Button)v).getText().toString().substring(6)));ex.addView(b);} col.addView(ex); list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);col.addView(list); setContentView(root); tick();}
  TextView t(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(0,8,0,8);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}
  EditText edit(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(Color.WHITE);e.setHintTextColor(0xff6b8490);e.setSingleLine(false);setup.addView(e);return e;}
  void addControls(){String[] modes={"Discover All","Target MAC","IRK Resolution"};Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,modes));setup.addView(mode); EditText mac=edit("Target MAC (AA:BB:CC:DD:EE:FF)",""); EditText irks=edit("IRK hex entries, one per line; separators/prefixes allowed",""); EditText name=edit("Name filter",""); EditText min=edit("Min RSSI dBm","-100"); EditText win=edit("RSSI averaging window","5"); EditText ref=edit("Reference RSSI @1m","-59"); EditText alert=edit("Proximity alert within meters (blank disabled)",""); CheckBox active=new CheckBox(this);active.setText("Active scan");active.setTextColor(Color.WHITE);active.setChecked(true);setup.addView(active); CheckBox continuous=new CheckBox(this);continuous.setText("Continuous scan");continuous.setTextColor(Color.WHITE);continuous.setChecked(true);setup.addView(continuous); CheckBox gps=new CheckBox(this);gps.setText("GPS stamping");gps.setTextColor(Color.WHITE);setup.addView(gps); Spinner env=new Spinner(this);env.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"indoor","outdoor","free_space"}));setup.addView(env); Button apply=new Button(this);apply.setText("APPLY SETUP");apply.setOnClickListener(v->{cfg.mode=mode.getSelectedItemPosition();cfg.mac=mac.getText().toString().trim().toUpperCase();cfg.irks=Rpa.parseIrks(irks.getText().toString());cfg.name=name.getText().toString();cfg.minRssi=num(min,-100);cfg.window=Math.max(1,num(win,5));cfg.ref=num(ref,-59);cfg.alert=alert.getText().length()==0?null:(double)num(alert,0);cfg.active=active.isChecked();cfg.continuous=continuous.isChecked();cfg.gps=gps.isChecked();cfg.env=env.getSelectedItem().toString();Toast.makeText(this,"Setup applied: "+cfg.irks.size()+" IRK(s)",0).show();});setup.addView(apply);}
  int num(EditText e,int d){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){return d;}}
  void requestPerms(){if(Build.VERSION.SDK_INT>=31)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.ACCESS_FINE_LOCATION},7);else requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},7);}
  void start(){requestPerms();BluetoothManager bm=getSystemService(BluetoothManager.class);BluetoothAdapter a=bm.getAdapter();if(a==null||!a.isEnabled()){startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));return;}scanner.ble=a.getBluetoothLeScanner();ScanSettings ss=new ScanSettings.Builder().setScanMode(cfg.active?ScanSettings.SCAN_MODE_LOW_LATENCY:ScanSettings.SCAN_MODE_LOW_POWER).build();scanner.ble.startScan(null,ss,scanner.cb);scanning=true;scanBtn.setText("STOP SCAN");}
  void stop(){if(scanner.ble!=null)try{scanner.ble.stopScan(scanner.cb);}catch(SecurityException ignored){} scanning=false;scanBtn.setText("START SCAN");}
  void tick(){radar.invalidate();render();h.postDelayed(this::tick,900);} void render(){ArrayList<Device> ds=new ArrayList<>(devices.values());ds.sort((a,b)->b.avg-a.avg);stats.setText((scanning?"Scanning":"Idle")+" • devices "+ds.size()+" • mode "+cfg.modeName());list.removeAllViews();for(Device d:ds){TextView v=t(d.name+"  "+d.addr+"\nRSSI "+d.rssi+" avg "+d.avg+" tx "+d.tx+" dist "+(d.dist==null?"?":String.format(Locale.US,"%.1fm",d.dist))+" seen "+d.count+" "+(d.resolved?"✓ resolved":"")+"\nUUIDs "+d.uuids+"\nMFG "+d.mfg,13,0xffe8fbff,false);v.setBackgroundColor(0x2210d8ff);v.setOnClickListener(x->Toast.makeText(this,"Pinned "+d.addr,0).show());list.addView(v);}}
  void share(String fmt){String out=Export.make(new ArrayList<>(devices.values()),fmt);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,out);startActivity(Intent.createChooser(i,"Share "+fmt));}
  class Scanner{BluetoothLeScanner ble;ScanCallback cb=new ScanCallback(){public void onScanResult(int t,ScanResult r){ingest(r);}};} 
  void ingest(ScanResult r){Device dev=r.getDevice();String addr;try{addr=dev.getAddress();}catch(SecurityException e){addr="unknown";}ScanRecord rec=r.getScanRecord();String nm=rec!=null&&rec.getDeviceName()!=null?rec.getDeviceName():"(unnamed)";if(cfg.name.length()>0&&!nm.toLowerCase().contains(cfg.name.toLowerCase()))return;if(cfg.mode==1&&!addr.equalsIgnoreCase(cfg.mac))return;if(r.getRssi()<cfg.minRssi)return;Device d=devices.getOrDefault(addr,new Device(addr));d.name=nm;d.rssi=r.getRssi();d.addRssi(r.getRssi(),cfg.window);d.tx=rec==null?Integer.MIN_VALUE:rec.getTxPowerLevel();d.dist=Distance.estimate(d.avg,d.tx==Integer.MIN_VALUE?cfg.ref:d.tx,cfg.env);d.count++;d.last=System.currentTimeMillis();if(d.first==0)d.first=d.last;d.uuids=rec==null?"":String.valueOf(rec.getServiceUuids());d.mfg=rec==null?"":rec.getManufacturerSpecificData().toString();d.resolved=cfg.mode==2&&Rpa.resolve(addr,cfg.irks);devices.put(addr,d);} 
  public static class SettingsModel{int mode=0,minRssi=-100,window=5,ref=-59;String mac="",name="",env="indoor";boolean active=true,continuous=true,gps=false;Double alert=null;List<byte[]> irks=new ArrayList<>();String modeName(){return new String[]{"All","Target","IRK"}[mode];}}
  public static class Device{String addr,name="",uuids="",mfg="";int rssi,avg,tx=Integer.MIN_VALUE,count;long first,last;Double dist;boolean resolved;ArrayDeque<Integer> hist=new ArrayDeque<>();Device(String a){addr=a;}void addRssi(int r,int w){hist.add(r);while(hist.size()>w)hist.remove();int s=0;for(int x:hist)s+=x;avg=s/hist.size();}}
  public static class Distance{static Double estimate(int rssi,int ref,String env){if(rssi==0)return null;double n=env.equals("free_space")?2.0:env.equals("outdoor")?2.7:3.2;return Math.pow(10.0,(ref-rssi)/(10*n));}}
  public static class Rpa{static List<byte[]> parseIrks(String s){ArrayList<byte[]> out=new ArrayList<>();for(String line:s.split("\\R")){String h=line.replaceAll("(?i)0x|[^0-9a-f]","");if(h.length()==32){byte[] b=new byte[16];for(int i=0;i<16;i++)b[i]=(byte)Integer.parseInt(h.substring(i*2,i*2+2),16);out.add(b);}}return out;}static boolean isRpa(byte[] a){return (a[5]&0xC0)==0x40;}static boolean resolve(String mac,List<byte[]> irks){try{String h=mac.replaceAll("[^0-9A-Fa-f]","");if(h.length()!=12)return false;byte[] a=new byte[6];for(int i=0;i<6;i++)a[i]=(byte)Integer.parseInt(h.substring(i*2,i*2+2),16);if(!isRpa(a))return false;byte[] pr={a[3],a[4],a[5]};for(byte[] irk:irks){Cipher c=Cipher.getInstance("AES/ECB/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(irk,"AES"));byte[] in=new byte[16];in[13]=pr[0];in[14]=pr[1];in[15]=pr[2];byte[] e=c.doFinal(in);if(e[13]==a[0]&&e[14]==a[1]&&e[15]==a[2])return true;}}catch(Exception ignored){}return false;}}
  public static class Export{static String iso(long ms){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",Locale.US).format(new Date(ms));}static String make(List<Device>d,String f){StringBuilder s=new StringBuilder();if(f.equals("CSV"))s.append("address,name,rssi,avg_rssi,tx_power,distance,times_seen,first_seen,last_seen,resolved,manufacturer_data,service_uuids\n");for(Device x:d){String j="{\"address\":\""+x.addr+"\",\"name\":\""+x.name+"\",\"rssi\":"+x.rssi+",\"avg_rssi\":"+x.avg+",\"txPower\":"+x.tx+",\"distance\":"+x.dist+",\"timesSeen\":"+x.count+",\"firstSeen\":\""+iso(x.first)+"\",\"lastSeen\":\""+iso(x.last)+"\",\"resolved\":"+x.resolved+"}"; if(f.equals("JSONL"))s.append(j).append('\n');else if(f.equals("JSON")){if(s.length()==0)s.append('[');else s.append(',');s.append(j);}else s.append(x.addr+","+x.name+","+x.rssi+","+x.avg+","+x.tx+","+x.dist+","+x.count+","+iso(x.first)+","+iso(x.last)+","+x.resolved+",\""+x.mfg+"\",\""+x.uuids+"\"\n");}if(f.equals("JSON"))s.append(']');return s.toString();}}
  public static class RadarView extends View{Paint p=new Paint(1);long start=System.currentTimeMillis();public RadarView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight(),cx=w/2,cy=h/2;Paint g=p;g.setStyle(Paint.Style.FILL);g.setShader(new RadialGradient(cx,cy,w/2,0xff102033,0xff05070d,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,g);g.setShader(null);g.setStyle(Paint.Style.STROKE);g.setStrokeWidth(2);g.setColor(0x6600e5ff);for(int r=80;r<w/2;r+=80)c.drawCircle(cx,cy,r,g);float a=((System.currentTimeMillis()-start)%3600)/10f;g.setStrokeWidth(7);g.setColor(0xaa00e5ff);c.drawLine(cx,cy,cx+(float)Math.cos(Math.toRadians(a))*w/2,cy+(float)Math.sin(Math.toRadians(a))*w/2,g);g.setStyle(Paint.Style.FILL);for(int i=0;i<18;i++){g.setColor(i%3==0?0xffff2d75:0xff00e5ff);c.drawCircle(cx+(float)Math.cos(i*2.1)*((i*37)%(w/2-40)+30),cy+(float)Math.sin(i*1.7)*((i*29)%(h/2-40)+30),6+(i%4),g);} }}
}
